"""Intermediate Representation for parsed code"""

from typing import Any, Optional
from dataclasses import dataclass, field


@dataclass(frozen=True)
class SourceMarker:
    """Represent synline marker in source generated by m4"""

    index: int  # Where in source it was located
    original_line: int  # line number in the original source
    original_file: str  # source file name

    def __repr__(self):
        return f"{self.index}:{self.original_file}:{self.original_line}"


@dataclass(frozen=True)
class Metadata:
    """Represents the origin of a token with in a file"""

    row: int = 0
    column: int = 0
    file: str = ""

    def __repr__(self):
        return f"{self.file}:{self.row}:{self.column}"


@dataclass
class Symbol:
    """Represents a label"""

    name: str
    module: Optional[str] = None
    metadata: Optional[Metadata] = None

    def __repr__(self):
        return repr(self.name)


@dataclass
class Number:
    """Represents a number, float or integer or hex"""

    value: int | float
    metadata: Optional[Metadata] = None

    def __repr__(self):
        return repr(self.value)


@dataclass
class String:
    value: str
    metadata: Optional[Metadata] = None

    def __repr__(self):
        return repr(self.value)


@dataclass
class Instruction:
    """Represents a single instruction"""

    op: str
    args: Any = None
    metadata: Optional[Metadata] = None

    def __repr__(self):
        return f"{self.op.upper()} {self.args if self.args is not None else ''}"


@dataclass
class TranslationUnit:
    """Represents a single parsed file before it's linked"""

    name: str  # Module name
    base_offset: int = 0
    instructions: list[Instruction] = field(default_factory=list)

    # Private labels defined inside a single source file.
    labels: dict[str, int] = field(default_factory=dict)

    # Symbols that other files have access to.
    exports: dict[str, int] = field(default_factory=dict)

    # Symbols that are defined in other files.
    extern: list[str] = field(default_factory=list)
